spring:
  sql:
    init:
      mode: EMBEDDED
  cloud:
    gcp:
      pubsub:
        enabled: true
        emulator-host: localhost:8050
        project-id: mirchi-dev
      spanner:
        enabled: true
        project-id: mirchi-dev
        instance-id: dev-inst
        database: dev-db
        emulator:
          enabled: true
        emulator-host: localhost:9010